:Author: Paul Ryan A. Santiago
:Email: psantiago@ateneo.edu
:Date: 30/03/2023
:Revision: version 1.3
:License: Public Domain

= Project: Envisense Bluno 2560

The Bluno Mega 2560 BLE is configured before usage

Use the code below:
[source,arduino]
----
void setup() {
  Serial.begin(115200);             //initial the Serial
}

void loop() {
  if (Serial.available())  {
    Serial.write(Serial.read());    //send what has been received
    Serial.println();               //print line feed character
  }
}
----
[%hardbreaks]

Configure the BLE through AT command
1. Open the Serial monitor. Select the `No line ending` and 115200 baud rate
2. Type `+++` and press send button
3. If the AT Command Mode is successfully Entered , you will receive `Enter AT Mode`
4. Select the `Both NL & CR`
5. Type or copy the AT command in the dialog
6. If the BLE is successfully configured , you will receive `OK`
7. If received `ERROR CMD` instead, try sending it again or you should check whether the command is correct or not.

NOTE: `CR+LF` means Carriage-Return and Line-Feed, which is the same meaning with `Both NL & CR` in Arduino Serial monitor, do not include the string `CR+LF` itself.

*AT+SETTING* change the default setting
`AT+SETTING=DEFAULT` Restore the default settings, same as PERIPHERAL mode

*AT+NAME* Set the name
`AT+NAME=?` Request the name of the BLE
`AT+NAME=EnviSense-001` Set the name of BLE to "EnviSense-001".The length is limited to 13 Bytes or below

*AT+UART* change the baud rate of UART
`AT+UART=?` Request the baud rate of UART (default: 115200,8,N,1)
`AT+UART=9600` Set the baud rate to 9600

NOTE: After changing the baudrate to 9600, adjust the baudrate of serial monitor to 9600 then.

8. USE `AT+EXIT` to exit AT Mode
[%hardbreaks]

[1] https://wiki.dfrobot.com/Bluno_SKU_DFR0267[https://wiki.dfrobot.com/Bluno_SKU_DFR0267 ^]
[2] https://www.dfrobot.com/product-1175.html[https://www.dfrobot.com/product-1175.html ^]
[%hardbreaks]

The GPRS Arduino Shield is configured before usage
D7 - Used if you select software serial port to communicate with GPRS Shield
D8 - Used if you select software serial port to communicate with GPRS Shield
D9 - Used for software control the power up or down of the SIM900

*** Put a jumper wire from pin D7, and D8 to D10, and D11 respectively

GPRS LED Indicator
LED                       |       Status       | Function
Power-on indicator(Green) |       Off          | Power of GPRS Shield is off
                          |       On           | Power of GPRS Shield is on
Status Indicator(Red)     |       Off          | Power off
                          |       On           | Power on
Net indicator(Green)      |       Off          | SIM900 is not working
                          | 64ms On/800ms Off  | SIM900 does not find the network
                          | 64ms On/3000ms Off | SIM900 finds the network
                          | 64ms On/300ms Off  | GPRS communication

Turn on through Software. If the JP is soldered,run the following code, the GPRS will POWER on or POWER off.
----
void power_ON_Down()
{
pinMode(9, OUTPUT); 
digitalWrite(9,LOW);
delay(1000);
digitalWrite(9,HIGH);
delay(2000);
digitalWrite(9,LOW);
delay(3000);
}

void powerDown()
{
pinMode(9, OUTPUT); 
digitalWrite(9,LOW);
delay(1000);
digitalWrite(9,HIGH);
delay(2000);
digitalWrite(9,LOW);
delay(3000);
}
----

The GPRS Shield is used UART protocol to communicate with an Arduino:
Users can use "AT+IPR=?" command to see supported baudrate, it will response a list of supported baudrate.
Users can use "AT+IPR=x" ("x" is value of supported baudrate) to set a fixed baud rate and save the configuration to non-volatile flash memory.

Normal power down procedure: Turn off the GPRS shield by sending AT command "AT+CPOWD=1" to SIM900 module.
When GPRS Shield power dowm in Normal power down procedure, the procedure lets the SIM900 log off from the network and allows the software to enter into a secure state and save data before completely disconnecting the power supply. Before the completion of the power down procedure the SIM900 will send out result code:

NORMAL POWER DOWN

[3] https://www.elecrow.com/wiki/index.php?title=GPRS/GSM_Shield_v1.0
[4] https://www.elecrow.com/wiki/images/2/20/SIM800_Series_AT_Command_Manual_V1.09.pdf

SIM900l GPRS sleep mode AT Commands
AT+CSCLK= 0, 1, 2

The SIM800L draws around 20mA in idle, but if you send it the following command then it goes into Slow Clock state drawing only around 1mA - (essentially asleep) and waits for a wakeup: 
AT+CSCLK=2

If you look at the SIM800 data sheet then it only mentions AT+CSCLK=0 and AT+CSCLK=1, and you then have to use the DTC pin to wake it up. However, 
I spotted that the SIM900 supported AT+CSCLK=2 where it then goes to sleep and awaits a signal on the serial port. I tried it and it works a charm, 
although best to put a delay(1000) after it before any microprocessor sleep code so that the serial command has time to go through before it sleeps. 
I spotted that without the delay the command sometimes doesn't make it through in time. 

[5] http://www.raviyp.com/sim900-sim800-sleep-mode-at-commands/
[6] https://groups.google.com/g/reading-hackspace/c/8PwIo7imD0k
