:Author: Paul Ryan A. Santiago
:Email: psantiago@ateneo.edu
:Date: 30/03/2023
:Revision: version 1.3
:License: Public Domain

= Project: Envisense Bluno 2560

The Bluno Mega 2560 BLE is configured before usage

Use the code below:
[source,arduino]
----
void setup() {
  Serial.begin(115200);             //initial the Serial
}

void loop() {
  if (Serial.available())  {
    Serial.write(Serial.read());    //send what has been received
    Serial.println();               //print line feed character
  }
}
----
[%hardbreaks]

Configure the BLE through AT command
1. Open the Serial monitor. Select the `No line ending` and 115200 baud rate
2. Type `+++` and press send button
3. If the AT Command Mode is successfully Entered , you will receive `Enter AT Mode`
4. Select the `Both NL & CR`
5. Type or copy the AT command in the dialog
6. If the BLE is successfully configured , you will receive `OK`
7. If received `ERROR CMD` instead, try sending it again or you should check whether the command is correct or not.

NOTE: `CR+LF` means Carriage-Return and Line-Feed, which is the same meaning with `Both NL & CR` in Arduino Serial monitor, do not include the string `CR+LF` itself.

*AT+SETTING* change the default setting
`AT+SETTING=DEFAULT` Restore the default settings, same as PERIPHERAL mode

*AT+NAME* Set the name
`AT+NAME=?` Request the name of the BLE
`AT+NAME=EnviSense-001` Set the name of BLE to "EnviSense-001".The length is limited to 13 Bytes or below

*AT+UART* change the baud rate of UART
`AT+UART=?` Request the baud rate of UART (default: 115200,8,N,1)
`AT+UART=9600` Set the baud rate to 9600

NOTE: After changing the baudrate to 9600, adjust the baudrate of serial monitor to 9600 then.

8. USE `AT+EXIT` to exit AT Mode
[%hardbreaks]

[1] https://wiki.dfrobot.com/Bluno_SKU_DFR0267[https://wiki.dfrobot.com/Bluno_SKU_DFR0267 ^]
[2] https://www.dfrobot.com/product-1175.html[https://www.dfrobot.com/product-1175.html ^]
[%hardbreaks]

